# This is a basic workflow to help you get started with Actions

name: PHPCS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: PHPCS
    runs-on: ubuntu-18.04
    # The type of runner that the job will run on
    container: saucalinc/reviewdog-php

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Make Symlinks
      - name: Sniff
        run: |
          export REVIEWDOG_GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          PHPCS_DIFF=$(mktemp)
          PHPCS_JSON=$(mktemp)
          GIT_DIFF=$(mktemp)
          phpcs --report-json="${PHPCS_JSON}" "${GITHUB_WORKSPACE}" || PHPCS_EXIT_CODE=$?

          pwd

          git branch -a

          git diff remotes/origin/${{ github.event.pull_request.base.ref }}

          cat "${PHPCS_JSON}" \
          | php -f "/rdjson-conv.php" \
          | reviewdog \
              -f=rdjsonl \
              -diff="git diff remotes/origin/${{ github.event.pull_request.base.ref }}" \
              -filter-mode="${INPUT_FILTER_MODE:-added}" \
              -fail-on-error="${INPUT_FAIL_ON_ERROR:-true}" \
              -level="${INPUT_LEVEL:-warning}" -tee || REVIEWDOG_EXIT_CODE=$?
          git stash -u && git stash drop
